### PR TITLE
ci: add repo-token to release workflow to enable tagged revisions

### PR DESCRIPTION
**Pull request by jnsgruk**
Add a new parameter to the release workflow so that tags can be created automatically for each released revision

### CODE REVIEW

**Review by soumyaDghosh — APPROVED** [review]

**Comment by soumyaDghosh** [comment]
@jnsgruk Can you check this particular workflow? It's failing for long now

**Comment by jnsgruk** [comment]
Hmm, interesting. It's not obvious to me why it fails. One thing is that there is no static `version` field defined, perhaps try that? Drop the `adopt-info` and just hard code the version in the snap? I wonder if there is a step later on that fails when trying to grok the version.

**Comment by soumyaDghosh** [comment]
Yes.. exactly!!! Thanks a lot!

https://github.com/snapcrafters/ci/blob/main/parse-snapcraft-yaml/action.yaml#L93

But, the problem is, the `adopt-info` can never be used. Can't we do something else?

**Comment by jnsgruk** [comment]
At the moment no, because it's much more difficult to automate the update of versions if we use `adopt-info`. If you want to prepare a PR I'm happy to review, or I can start one if you need a hand :) Let me know!

**Pull request merged**
