### PR TITLE
[Enhancement]: Added auto update and other automating workflows

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
@merlijn-sebrechts This can't be tested with this PR, as `craftctl` is used to set version, and the base is still `core18`.

**Comment by merlijn-sebrechts** [comment]
Can you rebase this pr to remove the merge conflicts?

**Comment by soumyaDghosh** [comment]
Done!

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM!

**Pull request merged**
