### PR TITLE
Add initial packaging

### PR DESCRIPTION
**Pull request by om26er**
We can update the README once we are sure things actually work.

### CODE REVIEW

**Comment by om26er** [comment]
@popey I think we can land that now. Though please also enable auto-builds for this snap in build.snapcraft.io and since its not a classic snap, please add me as a 'collaborator', so I can manage that snap as well.

**Comment by popey** [comment]
Unfortunately I can't release it just yet. There's a couple bugs in the build service which prevent me hooking it up properly. Once the web team have fixed those - which they're working on right now - we should be good to go.

**Comment by om26er** [comment]
@popey I believe build.snapcraft.io is now working properly, lets proceed.

**Comment by popey** [comment]
@om26er Sadly not. We're blocked on https://github.com/canonical-websites/build.snapcraft.io/issues/623

**Pull request merged**
